### ISSUE TITLE
Feature Request/Feedback: Different Templates fetched from repo

### ISSUE THREAD

**Issue by AlbertoCastelo** [xtreamsrl/jupytemplate#1]
Love the idea. I'm currently working in adding this feature to the JupyterLab in our company. In my case, I would like to be able to create a new notebook from a template in a repository. That is, I'm looking to support many template notebooks. Does this tool currently do it? Does it make sense for me to contribute a solution?

**Comment by donlelef** [comment]
Hi @AlbertoCastelo! Thank you for your feedback.

Currently, jupytemplate allows for a single, yet editable, template. Including the possibility of choosing a specific template from a collection would be a very nice feature.

If you want, feel free to contribute your solution. I would suggest to include a new item in the `Parameters` listed in the file `template.yml`, to allow the user to choose the template. Such parameters are read in `main.js` here:
`$.extend(true, params, Jupyter.notebook.config.data.template);`
and accessed like this:
`            
if (params.ask_title_change_if_untitled) {
    // Run when notebook is saved
    JupyterEvents.on('before_save.Notebook', prompt_name);
}
`

Of course, I'm more than open to any other solution!

**Comment by timkpaine** [comment]
@AlbertoCastelo https://github.com/jpmorganchase/jupyterlab_templates
