### ISSUE TITLE
can i setup it to work in vscode?

### ISSUE THREAD

**Issue by sensen1** [xtreamsrl/jupytemplate#2]
i followed the quick start, finished the installation in vscode. 

could i create a template notebook file within vscode? 

thanks.

**Comment by donlelef** [comment]
Hi @sensen1,

Sorry for the delay in the answer and regards from Italy! You could edit the notebooks and the templates in vs code, but you definitely need a working jupyter server to use the extension and its configuration.

Please feel free to ask any further question you may have.
