### ISSUE TITLE
How to install using conda

### ISSUE THREAD

**Issue by LeonardoGentile** [xtreamsrl/jupytemplate#7]
New to the conda env I've naively tried `conda install jupytemplate` but that didn't work.
Any instruction on conda installation?

**Comment by donlelef** [comment]
Hi @LeonardoGentile! Unfortunately, you currently cannot install jupytemplate using conda. But you can install it in a conda environment using pip.

**Comment by LeonardoGentile** [comment]
Right, It was as simple as `pip install jupytemplate` inside an activate conda env!

Grazie ;) 👍
